In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [108]:
class ExercícioNumpy():
    """
        Numpy

            1. Utilizando a biblioteca numpy siga as instruções abaixo:
                1. Crie um array 6x6 preenchido com zero
                2. Preencha o centro desse array com um array 4x4 preenchido com uns
                3. Preencha o centro desse array com um array 2x2 preenchido com dois
                4. Gere um segundo array 6x6 com números inteiros aleatórios entre 0 e 2.
                5. Subtraia o primeiro array pelo segundo
    """
    def __init__(self):
        self.array = np.zeros(
            shape=(6, 6),
            dtype=int,
        )
        self.array_4x4 = np.ones(
            shape=(4, 4),
            dtype=int,
        )
        self.array_2x2 = np.full(
            shape=(2, 2),
            fill_value=2,
            dtype=int,
        )
        self.array_random = np.random.randint(
            low=0, 
            high=2, 
            size=(6, 6),
            dtype=int
        )
        
    def criando_um_array_6x6(self):
        print(f'\n6x6:\n{self.array}')
    
    def inserindo_um_array_4x4_no_array_6x6(self):
        self.array[1:5, 1:5] = self.array_4x4
        print(f'\n4x4 in 6x6:\n{self.array}')

    def inserindo_um_array_2x2_no_array_4x4(self):
        self.array[2:4, 2:4] = self.array_2x2
        print(f'\n2x2 in 4x4 in 6x6:\n{self.array}')
    
    def gerando_uma_matriz_aleatoria(self):
        print(f'\nRandom:\n{self.array_random}')
    
    def subtraíndo_matrizes(self):
        resultado = self.array - self.array_random
        print(f'\n6x6 - 6x6_random:\n{resultado}')

In [109]:
if __name__ == '__main__':
    exercício_numpy = ExercícioNumpy()
    exercício_numpy.inserindo_um_array_4x4_no_array_6x6()
    exercício_numpy.inserindo_um_array_2x2_no_array_4x4()
    exercício_numpy.gerando_uma_matriz_aleatoria()
    exercício_numpy.subtraíndo_matrizes()


4x4 in 6x6:
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]

2x2 in 4x4 in 6x6:
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 2 2 1 0]
 [0 1 2 2 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]

Random:
[[0 1 1 0 0 1]
 [0 1 0 0 1 0]
 [1 0 0 0 0 1]
 [1 1 1 1 0 1]
 [1 1 1 0 0 0]
 [0 1 1 0 1 0]]

6x6 - 6x6_random:
[[ 0 -1 -1  0  0 -1]
 [ 0  0  1  1  0  0]
 [-1  1  2  2  1 -1]
 [-1  0  1  1  1 -1]
 [-1  0  0  1  1  0]
 [ 0 -1 -1  0 -1  0]]
