In [1]:
import numpy as np

In [56]:
class ManipulaçãoComArray():
    """
    Manipulação Com Array
    """
    def __init__(self):
        self.matriz = np.arange(0, 100)
        self.matriz_reshape = self.matriz.reshape(10, 10)
        self.matriz_newaxis = self.matriz[np.newaxis]

    def matriz_reshape_informações(self):
        print(
            f""" 
{'=='*17}
Matriz:
{self.matriz_reshape}
{'=='*17}
ndim: {self.matriz_reshape.ndim}
{'=='*17}
shape: {self.matriz_reshape.shape}
{'=='*17}
size: {self.matriz_reshape.size}
{'=='*17}
            """
            )

    def matriz_newaxis_informações(self):
        print(
            f""" 
{'=='*17}
Matriz:
{self.matriz_newaxis}
{'=='*17}
ndim: {self.matriz_newaxis.ndim}
{'=='*17}
shape: {self.matriz_newaxis.shape}
{'=='*17}
size: {self.matriz_newaxis.size}
{'=='*17}
            """
            )

In [57]:
if __name__ == "__main__":
    aula_115 = ManipulaçãoComArray()
    aula_115.matriz_reshape_informações()


 
Matriz:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
ndim: 2
shape: (10, 10)
size: 100
            
